server:
  port: 9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    active: dev
  application:
    name: MENU-DIRECTORY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/menudirectorydb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect